parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $gameFilesPath: '%kernel.project_dir%/games/'

    App\:
        resource: '../src/*'
        exclude: '../src/{Model,Exceptions,Tests,Kernel.php}'

    # App\Strategy\StrategyInterface: '@App\Strategy\TacticSetStrategy'
    App\Strategy\StrategyInterface: '@App\Strategy\WeightedTacticsStrategy'

    App\PathFinder\PathFinderInterface: '@App\PathFinder\FloydWarshallAlgorithm'

    App\Strategy\WeightedTacticsStrategy:
        arguments:
            - '@App\PathFinder\FloydWarshallAlgorithm'
            -
                'take near gold': '@App\Strategy\WeightedTactic\TakeNearGoldTactic'
                'find gold':      '@App\Strategy\WeightedTactic\FindGoldTactic'

                'take near beer': '@App\Strategy\WeightedTactic\TakeNearTavernTactic'
                'find tavern':    '@App\Strategy\WeightedTactic\FindTavernTactic'

                'attack hero':    '@App\Strategy\WeightedTactic\AttackWeakHeroTactic'
                'find hero':      '@App\Strategy\WeightedTactic\FindWeakHeroTactic'
                'avoid hero':     '@App\Strategy\WeightedTactic\AvoidStrongHeroTactic'

    App\Strategy\StrategyProvider:
        arguments:
            -
                t: '@App\Strategy\TacticSetStrategy'
                w: '@App\Strategy\WeightedTacticsStrategy'

