parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Model,Exceptions,Tests,Kernel.php}'

    # App\Strategy\StrategyInterface: '@App\Strategy\TacticSetStrategy'
    App\Strategy\StrategyInterface: '@App\Strategy\WeightedTacticsStrategy'

    App\PathFinder\PathFinderInterface: '@App\PathFinder\FloydWarshallAlgorithm'

    App\Strategy\WeightedTacticsStrategy:
        arguments:
            - '@App\PathFinder\FloydWarshallAlgorithm'
            -
                'take gold': '@App\Strategy\WeightedTactic\TakeGoldTactic'
                'take beer': '@App\Strategy\WeightedTactic\TakeBeerTactic'
                'attack hero': '@App\Strategy\WeightedTactic\AttackWeakHeroTactic'
                'avoid hero': '@App\Strategy\WeightedTactic\AvoidStrongHeroTactic'

    App\Strategy\StrategyProvider:
        arguments:
            -
                t: '@App\Strategy\TacticSetStrategy'
                w: '@App\Strategy\WeightedTacticsStrategy'

