parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Model,Exceptions,Tests,Kernel.php}'

    # App\Strategy\StrategyInterface: '@App\Strategy\TacticSetStrategy'
    # App\Strategy\StrategyInterface: '@App\Strategy\WeighedTacticsStrategy'

    App\Strategy\StrategyProvider:
        arguments:
            -
                - '@App\Strategy\TacticSetStrategy'
                - '@App\Strategy\WeighedTacticsStrategy'
